/* automatically generated by rust-bindgen */

///
#[repr(C)]
#[derive(Debug, Copy)]
pub struct _cef_main_args_t {
    pub argc: ::std::os::raw::c_int,
    pub argv: *mut *mut ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout__cef_main_args_t() {
    assert_eq!(::core::mem::size_of::<_cef_main_args_t>() , 16usize);
    assert_eq!(::core::mem::align_of::<_cef_main_args_t>() , 8usize);
}
impl Clone for _cef_main_args_t {
    fn clone(&self) -> Self { *self }
}
